name: AppSec Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Semgrep
        uses: semgrep/semgrep-action@v1
        with:
          config: auto

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@0.36.0
        with:
          image-ref: 'bkimminich/juice-shop:latest'
          format: 'table'
          exit-code: '0'

      - name: Save SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem  
          chmod 600 private_key.pem
      
      - name: Deploy Juice Shop to AWS
        run: |
          ssh -o StrictHostKeyChecking=no \
            -i private_key.pem \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker stop juice-shop || true
            docker rm juice-shop || true
           docker pull bkimminich/juice-shop:latest

            docker run -d \
              --name juice-shop \
              -p 80:3000 \
              bkimminich/juice-shop:latest

          EOF

      - name: Notify Shuffle
        run: |
          curl -X POST "${{ secrets.SHUFFLE_WEBHOOK }}" \
            -H "Content-Type: application/json" \
            -d '{
              "repo": "${{ github.repository }}",
              "commit": "${{ github.sha }}",
              "branch": "${{ github.ref_name }}",
              "actor": "${{ github.actor }}",
              "status": "completed"
            }'

