name: AppSec Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
 
jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Code
       uses: actions/checkout@v4
       with:
         fetch-depth: 0
    
     - name: Run Semgrep
       run: |
          docker run --rm -v "${{ github.workspace }}:/src" \
          returntocorp/semgrep semgrep \
          --config=auto \
          --sarif \
          --output=/src/semgrep.sarif \
          /src
 
     - name: Run Gitleaks
       run: |
          docker run --rm -v "${{ github.workspace }}:/path" \
          zricethezav/gitleaks:latest detect \
          --source="/path" \
          --report-path=/path/gitleaks.json \
          --report-format=json

     - name: Run Gitleaks
       run: |
         docker run --rm -v "${{ github.workspace }}:/path" \
         zricethezav/gitleaks:latest detect \
         --source="/path" \
         --report-path=/path/gitleaks.json \
         --report-format=json
